### ISSUE TITLE
Preguntas y comentarios a la exposición de Adolfo Marcelo y David Guerrero, «Git»

### ISSUE THREAD

**Issue by gwolf** [unamfi/sistop-2021-1#149]
Abro este foro como un espacio de discusión para la exposición que prepararon los alumnos Adolfo Marcelo y David Guerrero, «Git». El video está disponible en:

https://www.youtube.com/watch?v=HptZBVqQ-L8

Además de participar aquí, les pido que llenen la pequña encuesta que está disponible en:

https://www.questionpro.com/t/ARiwuZkmWx

**Comment by Pipo071** [comment]
Muy buena exposición compañeros, creo que hoy en día Git es una herramienta vital para muchos de nosotros, hasta ahora yo solo he utilizado GitHub pero he leído muy buenos comentarios de GitLab. 
En mi experiencia hasta este curso no había utilizado Git ¿Creen que al inicio de la carrera deberían de enseñarnos a trabajar con un manejador de versiones?

**Comment by JonCalzada** [comment]
Buenas tardes compañeros: ¿Que ventajas tiene git sobre otros sistemas de control de versiones?

**Comment by Adolf96** [comment]
> Muy buena exposición compañeros, creo que hoy en día Git es una herramienta vital para muchos de nosotros, hasta ahora yo solo he utilizado GitHub pero he leído muy buenos comentarios de GitLab.
> En mi experiencia hasta este curso no había utilizado Git ¿Creen que al inicio de la carrera deberían de enseñarnos a trabajar con un manejador de versiones?

Gracias compañero, y en lo personal creemos que es un complemento necesario debido a las rama de programacion que aprendemos durante la carrera ademas que como ingenieros en computation es un requerimiento desarrollar codigo y mantener un control de nuestros proyectos, por ejemplo nosotros participamos en un grupo de desarrollo de aplicaciones de la facultad llamado "UNAM MOBILE" en donde aprendimos a la de a fuerzas aprender usar git por que siempre están generando nuevos repositorios de cada proyecto, por lo que siendo honesto si es algo que debería ser necesario aprender para nuestros inicios en la carrera. por suerte no es una plataforma complicada de usar y como ya lo hemos visto termina siendo muy util para desarrollar proyectos como los tuvimos en esta materia.

**Comment by Adolf96** [comment]
> Buenas tardes compañeros: ¿Que ventajas tiene git sobre otros sistemas de control de versiones?

A pesar de que si hay una gran variedad de controladores de versiones que la mayoría cumplen con su objetivo de crear repositorios de trabajo y tener un cierto control sobre el, lo que el visualmente es reconocido de GIT es lo amigable que es con el usuario ademas tener un almacen de herramnientas mucho mas completo que otros tambien se le atribuyen una gran cantidad e comandos que facilitan el control de tareas dentro y fuera del repositorio. Un punto fuerte de Git es el hecho de poder trabajar sin conexión, por lo que si nosotros como desarrolladores nos encontraramos trabajando en zonas sin conexión, sin duda alguna es mejor utilizar Git al igual que el hecho de ser un sistema distribuido permite que cada usuario tenga una copia completa del repositorio, es decir que si por algún caso alguno queda corrupto, solo los cambios que hayan sido únicos para ese repositorio serán perdidos, cosa que muchos otros VCS no tienen y solo el repositorio central contiene el historial completo, por lo que los usuarios deben comunicarse a través de la red al repositorio central para obtener el historial de los archivos, son algunas de las tantas ventajas que tiene y de hecho hay mas razones que en la pagina de git mencionan que te hacen ver sus ventajas para usarlo: https://blog.coffeedevs.com/8-razones-para-usar-git/
