### ISSUE TITLE
Error con pull master

### ISSUE THREAD

**Issue by ZeroKuvo** [unamfi/sistop-2021-1#86]
Me sale un error al hacer pull prof master debido al nombre de un archivo que tiene un caracter reservado.

![Screenshot 2020-10-21 170706](https://user-images.githubusercontent.com/71785489/96794856-963c8b00-13c4-11eb-887a-3f1b462765b0.png)

**Comment by gwolf** [comment]
Ramses Rosario dijo [Wed, Oct 21, 2020 at 03:42:33PM -0700]:
> Me sale un error al hacer pull prof master debido al nombre de un archivo que tiene un caracter reservado.
> 
> ![Screenshot 2020-10-21 170706](https://user-images.githubusercontent.com/71785489/96794856-963c8b00-13c4-11eb-887a-3f1b462765b0.png)

¡Ups!

Listo, y alo corregí. Uno de los compañeros subió un archivo que
contenía el caracter '?' dentro de su nombre... Y eso no es legal para
Windows!

Saludos,
